package de.krazey.utcomp.dashboard.utcomp

data class UtcompDataSnapshot(
    var firmware: String = "?",
    var utcompPro: Boolean = false,

    var temperatureDsA: Float = Float.NaN,
    var temperatureDsB: Float = Float.NaN,
    var temperatureDsC: Float = Float.NaN,
    var temperatureDsD: Float = Float.NaN,
    var temperatureNtc1: Float = Float.NaN,
    var temperatureNtc2: Float = Float.NaN,
    var temperatureNtc3: Float = Float.NaN,
    var temperatureOutside: Float = Float.NaN,
    var temperatureInside: Float = Float.NaN,
    var temperatureEngine: Float = Float.NaN,
    var temperatureOil: Float = Float.NaN,
    var temperatureUser1: Float = Float.NaN,
    var temperatureUser2: Float = Float.NaN,

    var vssSpeed1s: Int = 0,
    var vssSpeed200ms: Int = 0,
    var distance: Float = Float.NaN,
    var distanceDt: Float = Float.NaN,
    var vssImp1s: Int = 0,
    var vssImp200ms: Int = 0,
    var vssImp180s: Long = 0,
    var vssImpPbTotal: Long = 0,
    var vssImpLpgTotal: Long = 0,

    var consumptionAvg: Float = Float.NaN,
    var consumptionCur: Float = Float.NaN,
    var fuelLeftPb: Float = Float.NaN,
    var fuelLeftLpg: Float = Float.NaN,
    var fuelTypeCurrent: Int = 0,
    var tripCplPb: Float = Float.NaN,
    var tripCplLpg: Float = Float.NaN,
    var tripCpkm: Float = Float.NaN,
    var injectionTime1s: Float = Float.NaN,
    var injectionTime180s: Float = Float.NaN,
    var injectionTimePbTotal: Float = Float.NaN,
    var injectionTimeLpgTotal: Float = Float.NaN,

    var adcInValCh0: Float = Float.NaN,
    var adcInValCh1: Float = Float.NaN,
    var adcInValCh2: Float = Float.NaN,
    var adcInValCh3: Float = Float.NaN,
    var adcInValCh4: Float = Float.NaN,
    var adcInValCh5: Float = Float.NaN,
    var adcInValCh6: Float = Float.NaN,
    var adcInValCh7: Float = Float.NaN,
    var vref: Int = 0,
    var loggerFlashAddrCur: Long = 0,
    var digOutUserState: Int = 0,
    var gearNo: Int = 0,

    var bar1: Float = Float.NaN,
    var bar2: Float = Float.NaN,
    var bar3: Float = Float.NaN,
    var afr1: Float = Float.NaN,
    var afr2: Float = Float.NaN,
    var egt1: Int = 0,
    var egt2: Int = 0,
    var egt3: Int = 0,
    var egt4: Int = 0,
    var egt5: Int = 0,
    var egt6: Int = 0,
    var rpm: Int = 0,

    var tripTravelTime1s: Long = 0,
    var ignitionTime1s: Long = 0,
    var tripCons: Float = Float.NaN,
    var tripDist: Float = Float.NaN,
    var tripQty: Float = Float.NaN,
    var tripCost: Float = Float.NaN,
    var tripVavg: Float = Float.NaN,
    var vmax: Int = 0,
)
